import CarrierDashboardScreen from '@/pages/Carrier/Dashobard/CarrierDashboardScreen';
import ProfileSettingsScreen from '@/pages/Carrier/Settings/ProfileSettingsScreen';
import { createPlaceholderScreen } from '@/navigation/createPlaceholderScreen';
import {
  systemPermissionKeys,
  tenantPermissionKeys,
} from '@/utils/constants/permissions';
import type { MobileAuthRoute } from './types';

export const carrierRoutes: MobileAuthRoute = {
  path: '/carriers/:carrierId',
  screenName: 'CarrierPortal',
  allowedSystemPermissions: [systemPermissionKeys.ANY],
  allowedTenantPermissions: [tenantPermissionKeys.ANY],
  description: 'Carrier Portal',
  screen: CarrierDashboardScreen,
  isShowOnSidebar: false,
  title: 'Carrier Portal',
  portalContext: 'carriers',
  portalIcon: 'truck',
  pathParams: ['carrierId'],
  childRoutes: [
    {
      path: '/carriers/:carrierId/dashboard',
      screenName: 'CarrierDashboard',
      allowedSystemPermissions: [systemPermissionKeys.ANY],
      allowedTenantPermissions: [tenantPermissionKeys.ANY],
      description: 'Carrier Dashboard',
      screen: CarrierDashboardScreen,
      isShowOnSidebar: true,
      title: 'Dashboard',
      icon: 'dashboard',
    },
    {
      path: '/carriers/:carrierId/load-requests',
      screenName: 'LoadRequests',
      allowedSystemPermissions: [systemPermissionKeys.ANY],
      allowedTenantPermissions: [tenantPermissionKeys.ANY],
      description: 'Load Requests',
      screen: createPlaceholderScreen(
        'Load Requests',
        'View and manage load requests.',
      ),
      isShowOnSidebar: true,
      title: 'Load Requests',
      icon: 'package',
    },
    {
      path: '/carriers/:carrierId/load-orders',
      screenName: 'LoadOrders',
      allowedSystemPermissions: [systemPermissionKeys.ANY],
      allowedTenantPermissions: [tenantPermissionKeys.ANY],
      description: 'Orders Management',
      screen: createPlaceholderScreen(
        'Orders',
        'Inbox, planning, dispatch, and delivered orders.',
      ),
      isShowOnSidebar: true,
      title: 'Orders',
      icon: 'cart',
      isCollapsible: true,
    },
    {
      path: '/carriers/:carrierId/brokerage',
      screenName: 'Brokerage',
      allowedSystemPermissions: [systemPermissionKeys.ANY],
      allowedTenantPermissions: [tenantPermissionKeys.ANY],
      description: 'Brokerage',
      screen: createPlaceholderScreen(
        'Brokerage',
        'Load board and brokerage workflows.',
      ),
      isShowOnSidebar: true,
      title: 'Brokerage',
      icon: 'briefcase',
      isCollapsible: true,
    },
    {
      path: '/carriers/:carrierId/master',
      screenName: 'CarrierMaster',
      allowedSystemPermissions: [systemPermissionKeys.ANY],
      allowedTenantPermissions: [tenantPermissionKeys.ANY],
      description: 'Master Data',
      screen: createPlaceholderScreen(
        'Master Data',
        'Vehicles, drivers, and reference data.',
      ),
      isShowOnSidebar: true,
      title: 'Master',
      icon: 'database',
      isCollapsible: true,
    },
    {
      path: '/carriers/:carrierId/materials',
      screenName: 'Materials',
      allowedSystemPermissions: [systemPermissionKeys.ANY],
      allowedTenantPermissions: [tenantPermissionKeys.ANY],
      description: 'Materials',
      screen: createPlaceholderScreen('Materials', 'Material types and rates.'),
      isShowOnSidebar: true,
      title: 'Materials',
      icon: 'box',
    },
    {
      path: '/carriers/:carrierId/fuel',
      screenName: 'Fuel',
      allowedSystemPermissions: [systemPermissionKeys.ANY],
      allowedTenantPermissions: [tenantPermissionKeys.ANY],
      description: 'Fuel',
      screen: createPlaceholderScreen('Fuel', 'Fuel surcharges and rates.'),
      isShowOnSidebar: true,
      title: 'Fuel',
      icon: 'fuel',
    },
    {
      path: '/carriers/:carrierId/fsc',
      screenName: 'Fsc',
      allowedSystemPermissions: [systemPermissionKeys.ANY],
      allowedTenantPermissions: [tenantPermissionKeys.ANY],
      description: 'FSC',
      screen: createPlaceholderScreen('FSC', 'Fuel surcharge configuration.'),
      isShowOnSidebar: true,
      title: 'FSC',
      icon: 'percent',
    },
    {
      path: '/carriers/:carrierId/billing',
      screenName: 'Billing',
      allowedSystemPermissions: [systemPermissionKeys.ANY],
      allowedTenantPermissions: [tenantPermissionKeys.ANY],
      description: 'Billing',
      screen: createPlaceholderScreen('Billing', 'Invoices and settlements.'),
      isShowOnSidebar: true,
      title: 'Billing',
      icon: 'receipt',
    },
    {
      path: '/carriers/:carrierId/onboarding',
      screenName: 'Onboarding',
      allowedSystemPermissions: [systemPermissionKeys.ANY],
      allowedTenantPermissions: [tenantPermissionKeys.ANY],
      description: 'Onboarding',
      screen: createPlaceholderScreen(
        'Onboarding',
        'Driver and carrier onboarding.',
      ),
      isShowOnSidebar: true,
      title: 'Onboarding',
      icon: 'user-plus',
    },
    {
      path: '/carriers/:carrierId/settings',
      screenName: 'CarrierSettings',
      allowedSystemPermissions: [systemPermissionKeys.ANY],
      allowedTenantPermissions: [tenantPermissionKeys.ANY],
      description: 'Settings',
      screen: ProfileSettingsScreen,
      isShowOnSidebar: true,
      title: 'Settings',
      icon: 'settings',
    },
  ],
};
